create table if not exists books (
  id bigint generated by default as identity primary key,
  title text not null unique,
  notes_on_outline_before text,
  outline text,
  notes_on_outline_after text,
  status_outline_notes text,
  final_review_notes_status text default 'no',
  book_output_status text default 'new',
  created_at timestamp with time zone default now()
);

create table if not exists chapters (
  id bigint generated by default as identity primary key,
  book_id bigint references books(id) on delete cascade,
  chapter_number integer not null,
  chapter_title text,
  chapter_goal text,
  chapter_notes_status text default 'no',
  chapter_notes text,
  chapter_text text,
  chapter_summary text,
  created_at timestamp with time zone default now()
);
